handlers = jp.cssj.logging.FileHandler, \
	java.util.logging.ConsoleHandler
	
# Logging levels by categories.
jp.cssj.level = INFO
jp.cssj.copper.access.level = FINE

# File
java.util.logging.FileHandler.level = INFO
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.encoding = UTF-8

# Console
java.util.logging.ConsoleHandler.level = WARNING
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

java.util.logging.SimpleFormatter.format=%1$tb %1$td %1$tT %4$s %2$s - %5$s%6$s%n

